# Generated by Django 2.2.2 on 2019-06-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commodityName', models.CharField(max_length=64)),
                ('attributes', models.CharField(max_length=256)),
                ('hashCode', models.CharField(max_length=80)),
                ('securityCode', models.CharField(max_length=10)),
                ('price', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('companyName', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('status', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('ip', models.CharField(max_length=32)),
                ('operation', models.CharField(max_length=64)),
                ('operatorPerson', models.CharField(max_length=40)),
                ('securityCode', models.CharField(max_length=10)),
                ('time', models.IntegerField(default=1560758246.3745162, verbose_name='更新时间戳')),
                ('commodityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protobufdata.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=64)),
                ('attributes', models.CharField(max_length=256)),
                ('commodityPrice', models.CharField(default=0, max_length=10)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protobufdata.Company')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protobufdata.CommodityCategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='companyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protobufdata.Company'),
        ),
    ]
