# Generated by Django 2.2.2 on 2019-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protobufdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditycategory',
            old_name='commodityPrice',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='source',
            name='time',
            field=models.IntegerField(default=1560758303.2489257, verbose_name='更新时间戳'),
        ),
    ]
